config/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include
from django.conf.urls.static import static
from config import settings
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from products.api import ProductViewSet, ProductReviewView
from orders.api import OrderViewSet, CartView
from users.api import RegisterView

router = DefaultRouter()
router.register(r"products", ProductViewSet, basename="product")
router.register(r"orders", OrderViewSet, basename="order")

urlpatterns = [
    path('', RedirectView.as_view(url='/products/', permanent=False)),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),

    # --- REST API ---
    path("api/", include(router.urls)),
    path("api/cart/", CartView.as_view(), name="api-cart"),
    path("api/products/<int:pk>/reviews/", ProductReviewView.as_view(), name="api-product-reviews"),

    # users & JWT
    path("api/users/register/", RegisterView.as_view(), name="api-register"),
    path("api/users/login/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/users/refresh/", TokenRefreshView.as_view(), name="token_refresh"),

    # OpenAPI/Swagger
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import cart_change, checkout, cart_detail, order_detail

app_name = 'orders'

urlpatterns = [
    path('cart/change/<int:product_id>/', cart_change, name='cart_change'),
    path('cart/', cart_detail, name='cart_detail'),
    path('checkout/', checkout, name='checkout'),
    path('order/<int:pk>/', order_detail, name='order_detail'),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

from .views import UserCreateView, AccountView, UserUpdateView

app_name = 'users'

urlpatterns = [
    # TODO: wrong success url
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html',
                                     next_page=reverse_lazy('products:product-list'),
                                     ), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('products:product-list'),
                                     ), name='logout'),
    path('account/', AccountView.as_view(), name='account'),
    path('update/<int:pk>', UserUpdateView.as_view(), name='update')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.validators import validate_phone


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    email = models.EmailField(unique=True)

    phone = models.CharField(max_length=20, null=True, blank=True, validators=[validate_phone])

    image = models.ImageField(upload_to='profile_images',
                              null=True, blank=True,
                              default='profile_images/default.png'
                              )

    city = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['email']

    def __str__(self) -> str:
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from typing import Any, Dict

UserModel = get_user_model()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('email', 'username', 'first_name', 'last_name', 'password1', 'password2')
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'example@gmail.com', 'class': 'Input'}),
            'username': forms.TextInput(attrs={'placeholder': 'Your username', 'class': 'Input'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'John', 'class': 'Input'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Smith', 'class': 'Input'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'qwerty123', 'class': 'Input'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'qwerty123', 'class': 'Input'})
        }

        labels = {
            'email': 'Email',
            'username': 'Username',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'password1': 'Password',
            'password2': 'Confirm Password'
        }

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()
        if cleaned_data is None:
            return {}
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data

    def clean_email(self) -> str:
        email = self.cleaned_data.get("email") or ""
        email = str(email)
        if UserModel.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'example@gmail.com', 'class': 'Input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'qwerty123', 'class': 'Input'}))


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('email', 'username', 'first_name', 'last_name', 'phone', 'city', 'address')
        widgets = {
            'email': forms.EmailInput(
                attrs={'placeholder': 'example@mail.com', 'class': 'Input'}),
            'username': forms.TextInput(
                attrs={'placeholder': 'Your username', 'class': 'Input'}),
            'first_name': forms.TextInput(
                attrs={'placeholder': 'John', 'class': 'Input'}),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Doe', 'class': 'Input'}),
            'phone': forms.TextInput(
                attrs={'placeholder': '+(123)1234567', 'class': 'Input'}),
            'city': forms.TextInput(
                attrs={'placeholder': 'City', 'class': 'Input'}),
            'address': forms.Textarea(
                attrs={'placeholder': 'Address', 'class': 'Textarea', 'rows': 3})
        }
        labels = {
            'email': 'Email',
            'username': 'Username',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'phone': 'Phone',
            'address': 'Address',
            'city': 'City',
        }

users/views.py
from typing import Any, Dict
from django.views.generic import CreateView, TemplateView, UpdateView
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from users.forms import UserRegistrationForm, UserUpdateForm
from users.mixins import LoginRequiredMixin
from users.models import User


class UserCreateView(CreateView):
    """Регистрация пользователя"""
    form_class = UserRegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class AccountView(LoginRequiredMixin, TemplateView):
    """Список заказов и информация об аккаунте"""
    template_name = 'users/account.html'
    allow_empty = True

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        assert self.request.user.is_authenticated
        user = self.request.user

        context['form'] = UserUpdateForm(instance=user)

        orders_qs = user.orders.order_by('-create_at')
        paginator = Paginator(orders_qs, 10)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        context['paginator'] = paginator
        context['orders'] = page_obj.object_list
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """Обновление информации в аккаунте"""
    queryset = User.objects.all()
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:account')

users/templates/users/account.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<main class="account-page-wrapper">
  <div class="account-container">
    <!-- Tabs Navigation -->
    <div class="account-tabs">
      <button class="account-tab active" data-tab-target="#order-history">Order History</button>
      <button class="account-tab" data-tab-target="#account-info">Account Information</button>
    </div>

    <!-- Tabs Content -->
    <div class="tab-content">
      <!-- Order History Panel -->
      <div id="order-history" class="tab-pane active">
        {% if orders %}
          <div class="order-history-table">
            <!-- Table Header -->
            <div class="order-table-header">
              <div class="order-table-cell">Order Details</div>
              <div class="order-table-cell">Order Status</div>
              <div class="order-table-cell">Total</div>
            </div>
            <!-- Table Body -->
            <div class="order-table-body">
              {% for order in orders %}
                <div class="order-table-row">
                  <div class="order-table-cell">
                    <a href="{% url 'orders:order_detail' order.id %}" class="order-id">#{{ order.id }}</a>
                    <span class="order-date">{{ order.create_at|date }}</span>
                  </div>
                  <div class="order-table-cell">
                    <span class="order-status">{{ order.status }}</span>
                  </div>
                  <div class="order-table-cell">
                    <span class="order-total">${{ order.total_price }}</span>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>

          <!-- Pagination (simplified) -->
          {% if page_obj.has_other_pages %}
            <div class="account-pagination">
              {% if page_obj.has_previous %}
                <a class="pagination-link-account" href="?page={{ page_obj.previous_page_number }}">← Previous</a>
              {% else %}
                <span class="pagination-link-account disabled">← Previous</span>
              {% endif %}

              <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
              </span>

              {% if page_obj.has_next %}
                <a class="pagination-link-account" href="?page={{ page_obj.next_page_number }}">Next →</a>
              {% else %}
                <span class="pagination-link-account disabled">Next →</span>
              {% endif %}
            </div>
          {% endif %}

        {% else %}
          <div style="display: flex; justify-content: center; padding: 1rem 0;">No orders yet</div>
        {% endif %}
      </div>

      <!-- Account Information Panel -->
      <div id="account-info" class="tab-pane">
        <div class="account-form-container">
          <h2 class="account-form-title">Personal Info</h2>
          <form id="account-info-form" action="{% url 'users:update' user.id %}" method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="checkout-form-group">
                {{ field.errors }}
                {{ field.label }}
                {{ field }}
              </div>
            {% endfor %}
            <button type="submit" class="button button--primary button--full-width">Save</button>
          </form>
          <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="button button--secondary button--full-width">Logout</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</main>
{% endblock %}

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register | Hop & Barley</title>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Link to your main CSS file -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<!-- Header -->
<header>
    <div class="header-container">
        <a href="home.html" class="header__logo">
            <img src="{% static 'img/logo.svg' %}" alt="Hop & Barley Logo">
            <p class="logo-text">Hop & Barley</p>
        </a>
        <nav class="header__nav">
            <ul>
                <li><a href="home.html">Products</a></li>
                <li><a href="guides-recipes.html">Guides & Recipes</a></li>
                <li><a href="#">Community</a></li>
                <li><a href="#">Resources</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>

        {% if user.is_authenticated %}
            <!-- Block for authorized user -->
            <div class="header__user-actions" id="auth-user">
                <a href="{% url 'users:account' %}" class="user-icon" aria-label="My Account">
                    <img src="{% static 'img/icons/User_alt.svg' %}" alt="User Account">
                </a>
                <a href="cart.html" class="cart-icon" aria-label="Shopping Cart">
                    <img src="{% static 'img/icons/Shopping_bag.svg' %}" alt="Shopping Cart">
                </a>
            </div>
        {% else %}
            <!-- Block for unauthorized user -->
            <div id="auth-guest">
                <a href="{% url 'users:login' %}" class="button button--secondary">Sign in</a>
                <a href="{% url 'users:register' %}" class="button button--primary">Register</a>
            </div>
        {% endif %}


    </div>
</header>

<!-- Main Content -->
{% block content %}
{% endblock %}

<!-- Footer -->
<footer>
    <img src="{% static 'img/background/image-footer.svg' %}" alt="Hop & Barley Hops Logo" class="footer__hops-logo">
    <nav class="footer__nav">
        <ul>
            <li><a href="#">Contact</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Community</a></li>
            <li><a href="#">Resources</a></li>
            <li><a href="#">License</a></li>
        </ul>
    </nav>
    <p class="footer__copyright">© Hop & Barley 2025. All rights reserved</p>
</footer>

<!-- Link to your main JavaScript file -->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<main class="auth-page-wrapper">
  <div class="auth-background">
    <img src="{% static 'img/background/pattern.jpg' %}" alt="Background pattern">
  </div>
  <div class="auth-form-container">
    <div class="auth-container auth-container--login">
      <div class="Legend">
        <h1 class="auth-title">Sign In</h1>
      </div>

      <form class="auth-form" id="login-form" method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
            <div class="error-message">{{ error }}</div>
          {% endfor %}
        {% endif %}

        {% for field in form %}
          <div class="InputField">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
                <div class="error-message">{{ error }}</div>
            {% endfor %}
          </div>
        {% endfor %}

        <div class="ButtonGroup">
          <button type="submit" class="button button--primary">Sign In</button>
        </div>

        <div class="TextLink">
          <a href="forgot_password.html">Forgot password?</a>
        </div>
      </form>

      <p class="auth-switch">Don’t have an account? <a href="{% url 'users:register' %}">Sign up</a></p>
    </div>
  </div>
</main>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<main class="auth-page-wrapper">
    <div class="auth-background">
        <img src="{% static 'img/background/pattern.jpg' %}" alt="Background pattern">
    </div>
    <div class="auth-form-container">
        <div class="auth-container auth-container--register">
            <div class="Legend">
                <h1 class="auth-title">Register</h1>
            </div>

            <form class="auth-form" id="register-form" method="post">
                {% csrf_token %}

                {% for field in form %}
                    <div class="InputField">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <div class="error-message">{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endfor %}

                <div class="CheckboxField">
                    <label class="checkbox-container">Remember me
                        <input type="checkbox" checked>
                        <span class="checkmark"></span>
                    </label>
                </div>

                <div class="ButtonGroup">
                    <button type="submit" class="button button--primary">Register</button>
                </div>
            </form>

            <p class="auth-switch">Already have an account? <a href="{% url 'users:login' %}">Sign in</a></p>
        </div>
    </div>
</main>
{% endblock %}